openapi: 3.1.0
info:
    title: CV App
    description: |-
        This is a server-side RESTful API for the **CV App**, built on the OpenAPI 3.1.0 specification.
        More information about interactive documentation can be found on [Swagger](https://swagger.io/).

        This project is designed to create and manage a database of users' CVs. It supports rich models for describing work experience, programming skills, language proficiency, and scientific interests. Thanks to strict typing and validation (via Pydantic), data can be easily serialized for storage in the database, including handling MongoDB ObjectIds. You can test all available endpoints and interact with the API directly in this interface.

        Some useful links:
        - [Production application server](https://api-cv-app-max-damir.onrender.com/)
        - [Official FastAPI documentation](https://fastapi.tiangolo.com/)
        - [OpenAPI 3.1.0 specification](https://spec.openapis.org/oas/v3.1.0.html)
    contact:
        name: Support Team
        email: maks.damir.itshi251@gmail.com
    version: 0.1.0
servers:
    - url: https://api-cv-app-max-damir.onrender.com/
      description: Production server (Render)
tags:
    - name: root
      description: Check server status
    - name: users-cvs
      description: Operations on users' CVs (CRUD)
paths:
    /:
        get:
            tags:
                - root
            summary: Root
            operationId: root__get
            responses:
                "200":
                    description: Successful Response
                    content:
                        application/json:
                            example:
                                status: ok
                "429":
                    description: Too Many Requests
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/APIErrorResponse"
                            example:
                                detail: Rate limit exceeded
    /api/v1/users-cvs/{user_id}:
        get:
            tags:
                - users-cvs
            summary: Get User Cv
            operationId: get_user_cv_api_v1_users_cvs__user_id__get
            parameters:
                - name: user_id
                  in: path
                  required: true
                  schema:
                      type: string
                      title: User Id
            responses:
                "200":
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/UserCVResponse"
                            example:
                                id: null
                                photo: null
                                personal_info:
                                    first_name: John
                                    last_name: Peterson
                                    email: email@example.com
                                    phone: "+41791234567"
                                    date_of_birth: "2005-04-15"
                                    nationality: Swiss
                                    country_of_residence: Switzerland
                                    gender: male
                                languages:
                                    [
                                        {
                                            name: English,
                                            proficiency: advanced,
                                        },
                                        {
                                            name: Ukrainian,
                                            proficiency: native,
                                        },
                                    ]
                                work_experience:
                                    [
                                        {
                                            job_title: Junior Python Developer,
                                            location: Zurich,
                                            company: Tech Studio,
                                            from_date: "2024-06-01",
                                            to_date: "2024-09-12",
                                            description: Developed backend APIs and worked with databases.,
                                        },
                                    ]
                                scientific_interests:
                                    [
                                        {
                                            name: Artificial Intelligence,
                                            description: Interested in machine learning and backend automation.,
                                        },
                                    ]
                                publications:
                                    [{ title: AI Future, authors: ["me"] }]
                                awards:
                                    [
                                        {
                                            title: Best Student Project,
                                            organization: School,
                                            date: "2023-05-20",
                                            description: Won an award for a software development project.,
                                        },
                                    ]
                                favorite_subjects_in_school:
                                    [mathematics, computer_science, physics]
                                programming_skills:
                                    [
                                        { language: Python, level: advanced },
                                        {
                                            language: JavaScript,
                                            level: intermediate,
                                        },
                                    ]
                                device_access:
                                    weekly_hours: 25
                                hobbies: [{ name: "Coding" }, { name: "Football" }]
                "400":
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/APIErrorResponse"
                            example:
                                detail: 1 is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string

                "404":
                    description: Not Found
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/APIErrorResponse"
                            example:
                                detail: CV not found.
                "500":
                    description: Internal Server Error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/APIErrorResponse"
                            example:
                                detail: Internal Server Error.
        patch:
            tags:
                - users-cvs
            summary: Update User Cv
            operationId: update_user_cv_api_v1_users_cvs__user_id__patch
            parameters:
                - name: user_id
                  in: path
                  required: true
                  schema:
                      type: string
                      title: User Id
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            type: object
                            additionalProperties: true
                            title: Fields To Update
                        example:
                            personal_info:
                                last_name: Peterson
                                preferred_name: John

            responses:
                "200":
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                type: object
                                additionalProperties: true
                                title: Response Update User Cv Api V1 Users Cvs  User Id  Put
                            example:
                                id: 507f1f77bcf86cd799439011
                                status: updated
                                updated_fields:
                                    personal_info:
                                        last_name: Peterson
                                        preferred_name: John

                "400":
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/APIErrorResponse"
                            example:
                                detail: 1 is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string

                "422":
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                oneOf:
                                    - $ref: "#/components/schemas/HTTPValidationError"
                                    - $ref: "#/components/schemas/UpdateValidationErrorResponse"
                            example:
                                detail:
                                    message: Some fields are not valid update paths.
                                    invalid_fields: ["house_number", "relatives"]
                                    allowed_fields:
                                        [
                                            "photo",
                                            "personal_info.first_name",
                                            "personal_info.last_name",
                                            "personal_info.preferred_name",
                                            "personal_info.email",
                                            "personal_info.phone",
                                            "personal_info.date_of_birth",
                                            "personal_info.nationality",
                                            "personal_info.country_of_residence",
                                            "personal_info.gender",
                                            "languages",
                                            "work_experience",
                                            "scientific_interests",
                                            "publications",
                                            "awards",
                                            "favorite_subjects_in_school",
                                            "programming_skills",
                                            "device_access.weekly_hours",
                                            "hobbies"
                                        ]

        put:
            tags:
                - users-cvs
            summary: Update User Cv
            operationId: update_user_cv_api_v1_users_cvs__user_id__put
            parameters:
                - name: user_id
                  in: path
                  required: true
                  schema:
                      type: string
                      title: User Id
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/UserCVRequest"
                        example:
                            photo: null
                            personal_info:
                                first_name: John
                                last_name: Peterson
                                email: email@example.com
                                phone: "+41791234567"
                                date_of_birth: "2005-04-15"
                                nationality: Swiss
                                country_of_residence: Switzerland
                                gender: male
                            languages:
                                [
                                    { name: English, proficiency: advanced },
                                    { name: Ukrainian, proficiency: native },
                                ]
                            work_experience:
                                [
                                    {
                                        job_title: Junior Python Developer,
                                        location: Zurich,
                                        company: Tech Studio,
                                        from_date: "2024-06-01",
                                        to_date: "2024-09-12",
                                        description: Developed backend APIs and worked with databases.,
                                    },
                                ]
                            scientific_interests:
                                [
                                    {
                                        name: Artificial Intelligence,
                                        description: Interested in machine learning and backend automation.,
                                    },
                                ]
                            publications: [{ title: AI Future, authors: ["me"] }]
                            awards:
                                [
                                    {
                                        title: Best Student Project,
                                        organization: School,
                                        date: "2023-05-20",
                                        description: Won an award for a software development project.,
                                    },
                                ]
                            favorite_subjects_in_school:
                                [mathematics, computer_science, physics]
                            programming_skills:
                                [
                                    { language: Python, level: advanced },
                                    {
                                        language: JavaScript,
                                        level: intermediate,
                                    },
                                ]
                            device_access:
                                weekly_hours: 25
                            hobbies: [{ name: "Coding" }, { name: "Football" }]

            responses:
                "200":
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                type: object
                                additionalProperties: true
                                title: Response Update User Cv Api V1 Users Cvs  User Id  Put
                            example:
                                id: 507f1f77bcf86cd799439011
                                status: updated
                                new_document:
                                    photo: null
                                    personal_info:
                                        first_name: John
                                        last_name: Peterson
                                        email: email@example.com
                                        phone: "+41791234567"
                                        date_of_birth: "2005-04-15"
                                        nationality: Swiss
                                        country_of_residence: Switzerland
                                        gender: male
                                    languages:
                                        [
                                            {
                                                name: English,
                                                proficiency: advanced,
                                            },
                                            {
                                                name: Ukrainian,
                                                proficiency: native,
                                            },
                                        ]
                                    work_experience:
                                        [
                                            {
                                                job_title: Junior Python Developer,
                                                location: Zurich,
                                                company: Tech Studio,
                                                from_date: "2024-06-01",
                                                to_date: "2024-09-12",
                                                description: Developed backend APIs and worked with databases.,
                                            },
                                        ]
                                    scientific_interests:
                                        [
                                            {
                                                name: Artificial Intelligence,
                                                description: Interested in machine learning and backend automation.,
                                            },
                                        ]
                                    publications:
                                        [{ title: AI Future, authors: ["me"] }]
                                    awards:
                                        [
                                            {
                                                title: Best Student Project,
                                                organization: School,
                                                date: "2023-05-20",
                                                description: Won an award for a software development project.,
                                            },
                                        ]
                                    favorite_subjects_in_school:
                                        [mathematics, computer_science, physics]
                                    programming_skills:
                                        [
                                            {
                                                language: Python,
                                                level: advanced,
                                            },
                                            {
                                                language: JavaScript,
                                                level: intermediate,
                                            },
                                        ]
                                    device_access:
                                        weekly_hours: 25
                                    hobbies: [{ name: "Coding" }, { name: "Football" }]

                "400":
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/APIErrorResponse"
                            example:
                                detail: 1 is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string

                "422":
                    description: Validation Error
                    content:
                        application/json:
                            schema:
                                oneOf:
                                    - $ref: "#/components/schemas/HTTPValidationError"
                                    - $ref: "#/components/schemas/UpdateValidationErrorResponse"
                            example:
                                detail:
                                    message: New document is not valid.

        delete:
            tags:
                - users-cvs
            summary: Delete User Cv
            operationId: delete_user_cv_api_v1_users_cvs__user_id__delete
            parameters:
                - name: user_id
                  in: path
                  required: true
                  schema:
                      type: string
                      title: User Id
            responses:
                "200":
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                type: object
                                additionalProperties:
                                    type: string
                                title: Response Delete User Cv Api V1 Users Cvs  User Id  Delete
                            example:
                                id: 507f1f77bcf86cd799439011
                                status: deleted
                "400":
                    description: Bad Request
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/APIErrorResponse"
                            example:
                                detail: 1 is not a valid ObjectId, it must be a 12-byte input or a 24-character hex string
                "404":
                    description: Not Found
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/APIErrorResponse"
                            example:
                                detail: CV not found.
                "500":
                    description: Internal Server Error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/APIErrorResponse"
                            example:
                                detail: Internal Server Error.

    /api/v1/users-cvs:
        get:
            tags:
                - users-cvs
            summary: Get All User Cvs
            operationId: get_all_user_cvs_api_v1_users_cvs_get
            parameters:
                - name: skip
                  in: query
                  required: false
                  schema:
                      type: integer
                      default: 0
                      title: Skip
                - name: limit
                  in: query
                  required: false
                  schema:
                      type: integer
                      maximum: 100
                      default: 10
                      title: Limit
            responses:
                "200":
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                type: object
                                additionalProperties:
                                    anyOf:
                                        - type: integer
                                        - type: array
                                          items:
                                              type: object
                                              additionalProperties: true
                                title: Response Get All User Cvs Api V1 Users Cvs Get
                            example:
                                total: 0
                                skip: 0
                                limit: 10
                                items: []
                "500":
                    description: Internal Server Error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/APIErrorResponse"
                            example:
                                detail: Internal Server Error.
        post:
            tags:
                - users-cvs
            summary: Create User Cv
            operationId: create_user_cv_api_v1_users_cvs_post
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/UserCVRequest"
                        example:
                            photo: null
                            personal_info:
                                first_name: John
                                last_name: Peterson
                                email: email@example.com
                                phone: "+41791234567"
                                date_of_birth: "2005-04-15"
                                nationality: Swiss
                                country_of_residence: Switzerland
                                gender: male
                            languages:
                                [
                                    { name: English, proficiency: advanced },
                                    { name: Ukrainian, proficiency: native },
                                ]
                            work_experience:
                                [
                                    {
                                        job_title: Junior Python Developer,
                                        location: Zurich,
                                        company: Tech Studio,
                                        from_date: "2024-06-01",
                                        to_date: "2024-09-12",
                                        description: Developed backend APIs and worked with databases.,
                                    },
                                ]
                            scientific_interests:
                                [
                                    {
                                        name: Artificial Intelligence,
                                        description: Interested in machine learning and backend automation.,
                                    },
                                ]
                            publications: [{ title: AI Future, authors: ["me"] }]
                            awards:
                                [
                                    {
                                        title: Best Student Project,
                                        organization: School,
                                        date: "2023-05-20",
                                        description: Won an award for a software development project.,
                                    },
                                ]
                            favorite_subjects_in_school:
                                [mathematics, computer_science, physics]
                            programming_skills:
                                [
                                    { language: Python, level: advanced },
                                    {
                                        language: JavaScript,
                                        level: intermediate,
                                    },
                                ]
                            device_access:
                                weekly_hours: 25
                            hobbies: [{ name: "Coding" }, { name: "Football" }]
            responses:
                "201":
                    description: Successful Response
                    content:
                        application/json:
                            schema:
                                type: object
                                additionalProperties:
                                    type: string
                                title: Response Create User Cv Api V1 Users Cvs Post
                            example:
                                id: 507f1f77bcf86cd799439011
                                status: created
                "500":
                    description: Internal Server Error
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/APIErrorResponse"
                            example:
                                detail: Internal Server Error.
components:
    schemas:
        APIErrorResponse:
            properties:
                detail:
                    type: string
                    title: Detail
            additionalProperties: false
            type: object
            required:
                - detail
            title: APIErrorResponse
        UpdateValidationErrorResponse:
            properties:
                detail:
                    properties:
                        message:
                            type: string
                            title: Message
                        invalid_fields:
                            items:
                                type: string
                            type: array
                            title: Invalid Fields
                        allowed_fields:
                            items:
                                type: string
                            type: array
                            title: Allowed Fields
                    additionalProperties: false
                    type: object
                    required:
                        - message
                    title: Update Validation Error
            additionalProperties: false
            type: object
            required:
                - detail
            title: UpdateValidationErrorResponse
        Award:
            properties:
                title:
                    type: string
                    maxLength: 100
                    minLength: 1
                    title: Title
                organization:
                    anyOf:
                        - type: string
                          maxLength: 100
                        - type: "null"
                    title: Organization
                date:
                    anyOf:
                        - type: string
                          format: date
                        - type: "null"
                    title: Date
                description:
                    anyOf:
                        - type: string
                          maxLength: 300
                          minLength: 10
                        - type: "null"
                    title: Description
            additionalProperties: false
            type: object
            required:
                - title
            title: Award
        DeviceAccess:
            properties:
                weekly_hours:
                    type: number
                    minimum: 0
                    title: Weekly Hours
            additionalProperties: false
            type: object
            required:
                - weekly_hours
            title: DeviceAccess
        Gender:
            type: string
            enum:
                - male
                - female
                - other
            title: Gender
        HTTPValidationError:
            properties:
                detail:
                    items:
                        $ref: "#/components/schemas/ValidationError"
                    type: array
                    title: Detail
            type: object
            title: HTTPValidationError
        Hobby:
            properties:
                name:
                    type: string
                    maxLength: 50
                    minLength: 1
                    title: Name
            additionalProperties: false
            type: object
            required:
                - name
            title: Hobby
        Job:
            properties:
                job_title:
                    type: string
                    maxLength: 50
                    minLength: 1
                    title: Job Title
                location:
                    type: string
                    maxLength: 50
                    minLength: 1
                    title: Location
                company:
                    type: string
                    maxLength: 50
                    minLength: 1
                    title: Company
                from_date:
                    type: string
                    format: date
                    title: From Date
                to_date:
                    anyOf:
                        - type: string
                          format: date
                        - type: "null"
                    title: To Date
                description:
                    anyOf:
                        - type: string
                          maxLength: 300
                          minLength: 10
                        - type: "null"
                    title: Description
            additionalProperties: false
            type: object
            required:
                - job_title
                - location
                - company
                - from_date
            title: Job
        Language:
            properties:
                name:
                    type: string
                    maxLength: 30
                    minLength: 1
                    title: Name
                proficiency:
                    $ref: "#/components/schemas/ProficiencyLevel"
            additionalProperties: false
            type: object
            required:
                - name
                - proficiency
            title: Language
        ProficiencyLevel:
            type: string
            enum:
                - beginner
                - elementary
                - intermediate
                - upper_intermediate
                - advanced
                - native
            title: ProficiencyLevel
        ProgrammingLevel:
            type: string
            enum:
                - beginner
                - intermediate
                - advanced
                - expert
            title: ProgrammingLevel
        ProgrammingSkill:
            properties:
                language:
                    type: string
                    maxLength: 50
                    minLength: 1
                    title: Language
                level:
                    $ref: "#/components/schemas/ProgrammingLevel"
            additionalProperties: false
            type: object
            required:
                - language
                - level
            title: ProgrammingSkill
        Publication:
            properties:
                title:
                    type: string
                    maxLength: 200
                    minLength: 1
                    title: Title
                journal:
                    anyOf:
                        - type: string
                          maxLength: 100
                        - type: "null"
                    title: Journal
                publication_date:
                    anyOf:
                        - type: string
                          format: date
                        - type: "null"
                    title: Publication Date
                authors:
                    items:
                        type: string
                    type: array
                    title: Authors
                url:
                    anyOf:
                        - type: string
                        - type: "null"
                    title: Url
            additionalProperties: false
            type: object
            required:
                - title
            title: Publication
        SchoolSubject:
            type: string
            enum:
                - mathematics
                - physics
                - chemistry
                - biology
                - computer_science
                - history
                - geography
                - literature
                - english
                - other
            title: SchoolSubject
        ScientificInterest:
            properties:
                name:
                    type: string
                    maxLength: 100
                    minLength: 1
                    title: Name
                description:
                    anyOf:
                        - type: string
                          maxLength: 300
                          minLength: 10
                        - type: "null"
                    title: Description
            additionalProperties: false
            type: object
            required:
                - name
            title: ScientificInterest
        UserCVRequest:
            properties:
                photo:
                    anyOf:
                        - type: string
                        - type: "null"
                    title: Photo
                personal_info:
                    $ref: "#/components/schemas/UserPersonalInfo"
                languages:
                    items:
                        $ref: "#/components/schemas/Language"
                    type: array
                    title: Languages
                work_experience:
                    items:
                        $ref: "#/components/schemas/Job"
                    type: array
                    title: Work Experience
                scientific_interests:
                    items:
                        $ref: "#/components/schemas/ScientificInterest"
                    type: array
                    title: Scientific Interests
                publications:
                    items:
                        $ref: "#/components/schemas/Publication"
                    type: array
                    title: Publications
                awards:
                    items:
                        $ref: "#/components/schemas/Award"
                    type: array
                    title: Awards
                favorite_subjects_in_school:
                    items:
                        $ref: "#/components/schemas/SchoolSubject"
                    type: array
                    title: Favorite Subjects In School
                programming_skills:
                    items:
                        $ref: "#/components/schemas/ProgrammingSkill"
                    type: array
                    title: Programming Skills
                device_access:
                    $ref: "#/components/schemas/DeviceAccess"
                hobbies:
                    items:
                        $ref: "#/components/schemas/Hobby"
                    type: array
                    title: Hobbies
            additionalProperties: false
            type: object
            required:
                - personal_info
                - languages
                - work_experience
                - scientific_interests
                - publications
                - awards
                - favorite_subjects_in_school
                - programming_skills
                - device_access
                - hobbies
            title: UserCVRequest
        UserCVResponse:
            properties:
                id:
                    anyOf:
                        - type: string
                        - type: "null"
                    title: Id
                photo:
                    anyOf:
                        - type: string
                        - type: "null"
                    title: Photo
                personal_info:
                    $ref: "#/components/schemas/UserPersonalInfo"
                languages:
                    items:
                        $ref: "#/components/schemas/Language"
                    type: array
                    title: Languages
                work_experience:
                    items:
                        $ref: "#/components/schemas/Job"
                    type: array
                    title: Work Experience
                scientific_interests:
                    items:
                        $ref: "#/components/schemas/ScientificInterest"
                    type: array
                    title: Scientific Interests
                publications:
                    items:
                        $ref: "#/components/schemas/Publication"
                    type: array
                    title: Publications
                awards:
                    items:
                        $ref: "#/components/schemas/Award"
                    type: array
                    title: Awards
                favorite_subjects_in_school:
                    items:
                        $ref: "#/components/schemas/SchoolSubject"
                    type: array
                    title: Favorite Subjects In School
                programming_skills:
                    items:
                        $ref: "#/components/schemas/ProgrammingSkill"
                    type: array
                    title: Programming Skills
                device_access:
                    $ref: "#/components/schemas/DeviceAccess"
                hobbies:
                    items:
                        $ref: "#/components/schemas/Hobby"
                    type: array
                    title: Hobbies
            additionalProperties: false
            type: object
            required:
                - personal_info
                - languages
                - work_experience
                - scientific_interests
                - publications
                - awards
                - favorite_subjects_in_school
                - programming_skills
                - device_access
                - hobbies
            title: UserCVResponse
        UserPersonalInfo:
            properties:
                first_name:
                    type: string
                    maxLength: 20
                    minLength: 1
                    title: First Name
                last_name:
                    type: string
                    maxLength: 20
                    minLength: 1
                    title: Last Name
                preferred_name:
                    anyOf:
                        - type: string
                          maxLength: 20
                          minLength: 1
                        - type: "null"
                    title: Preferred Name
                email:
                    type: string
                    format: email
                    title: Email
                phone:
                    type: string
                    maxLength: 15
                    minLength: 10
                    title: Phone
                date_of_birth:
                    type: string
                    format: date
                    title: Date Of Birth
                nationality:
                    type: string
                    maxLength: 20
                    minLength: 1
                    title: Nationality
                country_of_residence:
                    type: string
                    maxLength: 30
                    minLength: 1
                    title: Country Of Residence
                gender:
                    $ref: "#/components/schemas/Gender"
            additionalProperties: false
            type: object
            required:
                - first_name
                - last_name
                - email
                - phone
                - date_of_birth
                - nationality
                - country_of_residence
                - gender
            title: UserPersonalInfo
        ValidationError:
            properties:
                loc:
                    items:
                        anyOf:
                            - type: string
                            - type: integer
                    type: array
                    title: Location
                msg:
                    type: string
                    title: Message
                type:
                    type: string
                    title: Error Type
                input:
                    title: Input
                ctx:
                    type: object
                    title: Context
            type: object
            required:
                - loc
                - msg
                - type
            title: ValidationError
